---
coverage:
  status:
    project: off
    patch: off

flags:
  analyzer:
    paths:
      - app/analyzer/
    carryforward: true

  api:
    paths:
      - app/api/
    carryforward: true

  api-client:
    paths:
      - app/api-client/
    carryforward: true

  playout:
    paths:
      - app/playout/
    carryforward: true

  shared:
    paths:
      - lib/shared/
    carryforward: true

  worker:
    paths:
      - app/worker/
    carryforward: true
