---
services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etc/postgres:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-libretime}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-libretime}
    healthcheck:
      test: pg_isready -U libretime

  rabbitmq:
    image: rabbitmq:3.13-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-/libretime}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-libretime}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-libretime}
    healthcheck:
      test: nc -z 127.0.0.1 5672

  # icecast:
  #   image: ghcr.io/libretime/icecast:2.4.4
  #   ports:
  #     - 8000:8000
  #   environment:
  #     ICECAST_SOURCE_PASSWORD: ${ICECAST_SOURCE_PASSWORD:-hackme}  # Change me !
  #     ICECAST_ADMIN_PASSWORD: ${ICECAST_ADMIN_PASSWORD:-hackme}  # Change me !
  #     ICECAST_RELAY_PASSWORD: ${ICECAST_RELAY_PASSWORD:-hackme}  # Change me !

  frontend:
    build:
      context: .
      dockerfile: Dockerfile   # или путь к твоему
      args:
        LIBRETIME_VERSION: "dev-local"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    image: frontend:dev
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    volumes:
      - ./etc/config.yml:/etc/libretime/config.yml:ro
    environment:
      LIBRETIME_CONFIG_FILEPATH: /etc/libretime/config.yml
      LIBRETIME_LOG_FILEPATH: php://stderr
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
