---
#
# This file is used for development. It it not intended for production!
# See https://libretime.org/docs/developer-manual/development/environment/#docker-compose
#
services:
  postgres:
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  # icecast:
  #   ports:
  #     - 8000:8000
  #     - 8443:8443
  #   environment:
  #     ICECAST_MAX_SOURCES: 10
  #   volumes:
  #     - ./dev/certs:/certs
  #     - ./dev/icecast.xml:/etc/icecast.xml

  # mailpit:
  #   image: axllent/mailpit
  #   ports:
  #     - 8025:8025
  #     - 1025:1025

  frontend:
    ports:
      - 6517:9000

    volumes:
      - ./etc/config.yml:/etc/libretime/config.yml:ro
      # - ./legacy/public:/var/www/html/public:rw,cached
      - ./legacy:/var/www/echo/retime/libretime/legacy:rw,cached
      - /var/www/echo/retime/files:/var/www/echo/retime/files:rw,cached
