[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[dependency-groups]
build = [
  "setuptools",
  "wheel"
]
development = [
  "requests-mock>=1.10.0,<2",
  "types-requests>=2.31.0,<3"
]

[project]
authors = [{name = "LibreTime Contributors"}]
dependencies = [
  "celery==4.4.7",
  "kombu==4.6.11",
  "mutagen>=1.45.1,<1.48",
  "requests>=2.32.2,<2.33",
  "sentry-sdk>=1.15.0,<2"
]
description = "LibreTime Worker"
license = {text = "MIT"}
name = "libretime-worker"
requires-python = ">=3.10"
version = "4.5.0"

[project.scripts]
libretime-worker = "libretime_worker.main:cli"

[project.urls]
"Bug Tracker" = "https://github.com/libretime/libretime/issues"
Documentation = "https://libretime.org"
Homepage = "https://github.com/libretime/libretime"
"Source Code" = "https://github.com/libretime/libretime"

[ruff.lint.isort]
known-first-party = [
  "libretime_analyzer",
  "libretime_api",
  "libretime_api_client",
  "libretime_playout",
  "libretime_shared"
]
known-third-party = [
  "celery",
  "kombu",
  "mutagen",
  "requests",
  "sentry_sdk"
]

[tool.setuptools]
packages = ["libretime_worker"]
