[project]
name = "libretime-api"
version = "4.5.0"
requires-python = ">=3.10"
description = "LibreTime API"
authors = [{ name = "LibreTime Contributors" }]
license = { text = "AGPLv3" }
dependencies = [
    "django>=4.2.0,<4.3",
    "django-cors-headers>=3.14.0,<4.5",
    "django-filter>=2.4.0,<24.4",
    "djangorestframework>=3.14.0,<3.16",
    "drf-spectacular>=0.22.1,<0.29",
    "gunicorn>=22.0.0,<23.1",
    "psycopg[binary]>=3.1.8,<3.3",
    "requests>=2.32.2,<2.33",
    "sentry-sdk[django]>=1.15.0,<2",
    "uvicorn[standard]>=0.17.6,<0.36.0",
]

[dependency-groups]
build = [
  "setuptools",
  "wheel"
]
development = [
  "django-coverage-plugin>=3.0.0,<4",
  "django-stubs>=5.1.0,<6",
  "djangorestframework-stubs>=1.8.0,<4",
  "model_bakery>=1.10.1,<2",
  "psycopg[binary]>=3.1.8,<3.3",
  "pylint-django>=2.5.3,<3",
  "pytest-django>=4.5.2,<5",
  "requests-mock>=1.10.0,<2",
]

[project.urls]
Homepage = "https://github.com/libretime/libretime"
"Bug Tracker" = "https://github.com/libretime/libretime/issues"
Documentation = "https://libretime.org"
"Source Code" = "https://github.com/libretime/libretime"

[project.scripts]
libretime-api = "libretime_api.manage:main"

[tool.django-stubs]
django_settings_module = "libretime_api.settings.testing"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "libretime_api.settings.testing"

[tool.coverage.run]
plugins = ["django_coverage_plugin"]
source = ["libretime_api"]
omit = [
  "*/migrations/*",
  "*/tests/*",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["libretime_*"]
