[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[dependency-groups]
build = [
  "setuptools",
  "wheel"
]
development = [
  "types-backports>=0.1.3,<1",
  "types-pyyaml>=5.3.1,<7"
]

[project]
authors = [{name = "LibreTime Contributors"}]
dependencies = [
  "backports-zoneinfo>=0.2.1,<0.3 ; python_full_version < '3.9'",
  "click>=8.0.4,<8.2",
  "pydantic>=2.5.0,<2.12",
  "pyyaml>=5.3.1,<6.1"
]
description = "LibreTime Shared SDK"
license = {text = "AGPLv3"}
name = "sdk"
requires-python = ">=3.10"
version = "4.5.0"

[project.urls]
"Bug Tracker" = "https://github.com/libretime/libretime/issues"
Documentation = "https://libretime.org"
Homepage = "https://github.com/libretime/libretime"
"Source Code" = "https://github.com/libretime/libretime"

[ruff.lint.isort]
known-first-party = [
  "click",
  "pydantic",
  "pytest",
  "pyyaml"
]

[tool.mypy]
allow_redefinition = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true

[tool.setuptools]
packages = ["sdk"]
