[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[tool.isort]
combine_as_imports = true
profile = "black"

[tool.mypy]
allow_redefinition = true
disallow_incomplete_defs = true

[tool.pylint.messages_control]
disable = [
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring"
]
extension-pkg-whitelist = "pydantic"
