[project]
name = "libretime-analyzer"
version = "4.5.0"
requires-python = ">=3.10"
description = "LibreTime Analyzer"
authors = [{ name = "LibreTime Contributors" }]
license = { text = "AGPLv3" }
dependencies = [
    "mutagen>=1.45.1,<1.48",
    "pika>=1.0.0,<1.4",
    "requests>=2.32.2,<2.33",
    "sentry-sdk>=1.15.0,<2",
    "typing-extensions>=4.15.0",
]

[dependency-groups]
build = [
  "setuptools",
  "wheel"
]
development = [
  "distro>=1.8.0,<2",
  "types-requests>=2.31.0,<3"
]

[project.urls]
Homepage = "https://github.com/libretime/libretime"
"Bug Tracker" = "https://github.com/libretime/libretime/issues"
Documentation = "https://libretime.org"
"Source Code" = "https://github.com/libretime/libretime"

[project.scripts]
libretime-analyzer = "libretime_analyzer.main:cli"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["libretime_*"]
