[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[dependency-groups]
build = [
  "setuptools",
  "wheel"
]
development = [
  "distro>=1.8.0,<2",
  "types-requests>=2.31.0,<3"
]

[project]
authors = [{name = "LibreTime Contributors"}]
dependencies = [
  "mutagen>=1.45.1,<1.48",
  "pika>=1.0.0,<1.4",
  "requests>=2.32.2,<2.33",
  "sentry-sdk>=1.15.0,<2",
  "typing-extensions>=4.15.0"
]
description = "LibreTime Analyzer"
license = {text = "AGPLv3"}
name = "libretime-analyzer"
requires-python = ">=3.10"
version = "4.5.0"

[project.scripts]
libretime-analyzer = "libretime_analyzer.main:cli"

[project.urls]
"Bug Tracker" = "https://github.com/libretime/libretime/issues"
Documentation = "https://libretime.org"
Homepage = "https://github.com/libretime/libretime"
"Source Code" = "https://github.com/libretime/libretime"

[tool.setuptools.packages.find]
include = ["libretime_analyzer"]
where = ["."]

[ruff.lint.isort]
known-first-party = [
  "libretime_api",
  "libretime_api_client",
  "libretime_shared",
  "libretime_worker"
]
known-third-party = [
  "mutagen",
  "pika",
  "requests",
  "sentry_sdk"
]
